# Generated by Django 5.1.7 on 2026-05-02 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0003_alter_pedido_status_entrega_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carrinhoitem",
            old_name="imagem_selecionada",
            new_name="imagem",
        ),
    ]
