# Generated by Django 5.2 on 2025-08-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('lancamentos', 'Lançamentos'), ('promocoes', 'Promoções'), ('conjuntos', 'Conjuntos'), ('outros', 'Outros')], default='outros', max_length=20, verbose_name='Categoria'),
        ),
    ]
