# Generated by Django 5.2 on 2025-09-04 12:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_enderecoentrega_pedido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-data_criacao']},
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='data_atualizacao',
        ),
        migrations.AddField(
            model_name='pedido',
            name='frete',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_mercado_pago',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pagamento',
            field=models.CharField(choices=[('pix', 'PIX'), ('cartao', 'Cartão de Crédito')], default='pix', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('retirada', 'Retirada na Loja'), ('entrega', 'Entrega')], default='retirada', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='endereco_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.enderecoentrega'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('processando', 'Processando'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
    ]
