# Generated by Django 5.2 on 2025-09-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_alter_pedido_options_remove_pedido_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enderecoentrega',
            options={'verbose_name_plural': 'Endereços de Entrega'},
        ),
        migrations.AlterUniqueTogether(
            name='carrinhoitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nome_cartao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero_cartao',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='validade_cartao',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='carrinhoitem',
            name='cor_selecionada',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='carrinhoitem',
            name='data_adicionado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='carrinhoitem',
            name='tamanho_selecionado',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
