# Generated by Django 5.2 on 2025-09-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0008_alter_itempedido_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='itens',
            field=models.ManyToManyField(to='vendas.carrinhoitem'),
        ),
        migrations.DeleteModel(
            name='ItemPedido',
        ),
    ]
