# Generated by Django 5.2 on 2025-09-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0010_remove_pedido_itens_itempedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='qr_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='qr_code_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
