# Generated by Django 5.2 on 2025-09-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0011_pedido_qr_code_pedido_qr_code_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aguardando_aprovacao', 'Aguardando Aprovação'), ('aprovado', 'Aprovado'), ('processando', 'Processando'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
    ]
