# Generated by Django 5.2 on 2025-09-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0012_alter_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinhoitem',
            name='imagem_selecionada',
            field=models.ImageField(blank=True, null=True, upload_to='carrinho/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tamanho',
            field=models.CharField(choices=[('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('U', 'Único')], default='M', max_length=10, verbose_name='Tamanho'),
        ),
    ]
