# Generated by Django 5.2 on 2025-09-19 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0013_carrinhoitem_imagem_selecionada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinhoitem',
            name='imagem_selecionada',
        ),
    ]
