# Generated by Django 5.2 on 2025-09-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0014_remove_carrinhoitem_imagem_selecionada'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinhoitem',
            name='imagem_selecionada',
            field=models.ImageField(blank=True, null=True, upload_to='carrinho/'),
        ),
    ]
